In [1]:
import wearipedia
import pandas as pd
import json
import http.cookiejar as cookiejar
from dotenv import load_dotenv
import os

In [2]:
# === CONFIGURATION ===
load_dotenv('.env/.env')
email_address = os.getenv(f'CRONOMETER_EMAIL')
password = os.getenv(f'CRONOMETER_PASSWORD')

#@title Enter start and end dates (in the format yyyy-mm-dd)
#set start and end dates - this will give you all the data from 2000-01-01 (January 1st, 2000) to 2100-02-03 (February 3rd, 2100), for example
start_date='2025-03-01' #@param {type:"string"}
end_date='2025-09-17' #@param {type:"string"}
synthetic = False #@param {type:"boolean"}

In [3]:
device = wearipedia.get_device("cronometer/cronometer")

if not synthetic:
    device.authenticate({"username": email_address, "password": password})

params = {"start_date": start_date, "end_date": end_date}

Authentication successful

In [4]:
dailySummary_data = device.get_data("dailySummary", params=params)
dailySummary_df = pd.DataFrame(dailySummary_data)
dailySummary_df.head()

,Date,Energy (kcal),Alcohol (g),Caffeine (mg),Water (g),B1 (Thiamine) (mg),B2 (Riboflavin) (mg),B3 (Niacin) (mg),B5 (Pantothenic Acid) (mg),B6 (Pyridoxine) (mg),...,Leucine (g),Lysine (g),Methionine (g),Phenylalanine (g),Protein (g),Threonine (g),Tryptophan (g),Tyrosine (g),Valine (g),Completed
0,2025-04-23,1583.92,0.0,142.08,1201.54,4.50,3.64,50.25,7.23,6.66,...,5.19,5.32,1.53,2.67,139.95,2.91,0.66,2.17,3.45,False
1,2025-04-24,1219.05,0.0,142.08,353.03,3.05,2.27,30.68,4.90,5.00,...,0.02,0.00,0.00,0.01,99.56,0.00,0.00,0.01,0.01,False
2,2025-04-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,2025-04-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,2025-04-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [5]:
servings_data = device.get_data("servings", params=params)
servings_df = pd.DataFrame(servings_data)
servings_df.head()

,Day,Time,Group,Food Name,Amount,Energy (kcal),Alcohol (g),Caffeine (mg),Water (g),B1 (Thiamine) (mg),...,Leucine (g),Lysine (g),Methionine (g),Phenylalanine (g),Protein (g),Threonine (g),Tryptophan (g),Tyrosine (g),Valine (g),Category
0,2025-04-23,NaN,Breakfast,Protein and Berries,1.00 full recipe,349.20,0.0,0.00,392.96,0.12,...,0.08,0.05,0.02,0.05,35.15,0.06,0.01,0.04,0.06,NaN
1,2025-04-23,NaN,Breakfast,Daily Supplements,1.00 full recipe,95.00,0.0,0.00,0.00,3.00,...,0.00,0.00,0.00,0.00,2.00,0.00,0.00,0.00,0.00,NaN
2,2025-04-23,NaN,Breakfast,"Coffee, Prepared From Grounds",1.00 small or tall - each 12 fl oz,3.55,0.0,142.08,353.03,0.05,...,0.02,0.00,0.00,0.01,0.43,0.00,0.00,0.01,0.01,Beverages
3,2025-04-23,NaN,Breakfast,"Nestle, Coffee Mate, Thai Iced Coffee, The Whi...",1.00 tbsp,30.00,NaN,NaN,8.79,NaN,...,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,Beverages
4,2025-04-23,NaN,Lunch,"Salad and Go, Mixed Greens",6.00 x 1.85 oz,60.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.00,NaN,NaN,NaN,NaN,Restaurant Foods

In [6]:
exercises_data = device.get_data("exercises", params=params)
exercises_df = pd.DataFrame(exercises_data)
exercises_df.head()

,Day,Time,Group,Exercise,Minutes,Calories Burned
0,2025-04-23,NaN,Uncategorized,Daily Activity (Garmin),161.00,-594.00
1,2025-04-24,NaN,Uncategorized,Daily Activity (Garmin),194.00,-529.00
2,2025-04-25,NaN,Uncategorized,Daily Activity (Garmin),142.00,-384.00
3,2025-04-25,7:29 AM,Uncategorized,Walking (Garmin),16.15,-45.46
4,2025-04-25,9:09 AM,Uncategorized,Treadmill running (Garmin),30.10,-237.04

In [7]:
biometrics_data = device.get_data("biometrics", params=params)
biometrics_df = pd.DataFrame(biometrics_data)
biometrics_df.head(20)

           Day      Time          Group               Metric Unit  Amount
0   2025-04-23       NaN  Uncategorized               Weight  lbs   120.0
1   2025-04-23       NaN  Uncategorized    Recovery (Garmin)    %    87.0
2   2025-04-23  12:00 AM  Uncategorized  Heart Rate (Garmin)  bpm    46.0
3   2025-04-23  12:00 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
4   2025-04-23  12:00 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
5   2025-04-23  12:00 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
6   2025-04-23  12:00 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
7   2025-04-23  12:00 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
8   2025-04-23  12:00 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
9   2025-04-23  12:01 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
10  2025-04-23  12:01 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
11  2025-04-23  12:01 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
12  2025-04-23  12:01 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
13  2025-04-23  12:01 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
14  2025-04-23  12:01 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
15  2025-04-23  12:01 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
16  2025-04-23  12:01 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
17  2025-04-23  12:02 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
18  2025-04-23  12:02 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0
19  2025-04-23  12:02 AM  Uncategorized  Heart Rate (Garmin)  bpm    44.0

In [8]:
from http.cookiejar import Cookie, CookieJar

def build_cookiejar_from_json(json_path: str) -> CookieJar:
    with open(json_path, "r") as f:
        cookies_data = json.load(f)

    jar = CookieJar()

    for c in cookies_data:
        cookie = Cookie(
            version=0,
            name=c["name"],
            value=c["value"],
            port=None,
            port_specified=False,
            domain=c["domain"],
            domain_specified=True,
            domain_initial_dot=c["domain"].startswith("."),
            path=c["path"],
            path_specified=True,
            secure=c.get("secure", False),
            expires=c.get("expires"),
            discard=False,
            comment=None,
            comment_url=None,
            rest=c.get("rest", {}),
            rfc2109=False,
        )
        jar.set_cookie(cookie)

    return jar

In [9]:
cookie_filepath = ".env/cookies.json"
jar2 = build_cookiejar_from_json(cookie_filepath)

device = wearipedia.get_device("myfitnesspal/myfitnesspal")

if not synthetic:
    device.authenticate({'cookies': jar2})

params = {"start_date": start_date, "end_date": end_date}

MyfitnesspalRequestFailed: Unable to fetch authentication token from MyFitnessPal: status code: 403